const pool = [
  {categorie:"Incident",abstraction:"Ã©vÃ©nement",consigne:"Ton hÃ©ros se met Ã  saigner du nez sans raison."},
  {categorie:"Alerte",abstraction:"bruit",consigne:"Une alarme retentit soudain tout prÃ¨s."},
  {categorie:"Douleur",abstraction:"physique",consigne:"Un personnage a une rage de dents fulgurante."},
  {categorie:"Musique",abstraction:"ambiance",consigne:"Ajoute une musique (connue ou inventÃ©e) Ã  la scÃ¨ne, qui change la perception des personnages."},
  {categorie:"Intrus",abstraction:"animal",consigne:"Un animal (chien, chat, oiseau...) surgit dans la scÃ¨ne, tout le monde doit rÃ©agir."},
  {categorie:"Erreur",abstraction:"action",consigne:"Un personnage brise un objet auquel il tenait beaucoup."},
  {categorie:"Climat",abstraction:"mÃ©tÃ©o",consigne:"Un orage Ã©clate, forÃ§ant les personnages Ã  sâ€™abriter."},
  {categorie:"Choc",abstraction:"Ã©vÃ©nement",consigne:"Quelquâ€™un tombe dans les pommes, sans prÃ©venir."},
  {categorie:"Surprise",abstraction:"objet",consigne:"Un objet inattendu est dÃ©couvert dans un sac ou une poche."},
  {categorie:"Attente",abstraction:"tension",consigne:"Un personnage attend un appel qui ne vient jamais."},
  {categorie:"Geste",abstraction:"action",consigne:"Un geste anodin dÃ©clenche une rÃ©action disproportionnÃ©e."},
  {categorie:"Coupure",abstraction:"structure",consigne:"La scÃ¨ne est interrompue par un bruit violent (explosion, fracas, hurlementâ€¦)."},
  {categorie:"RÃ©pÃ©tition",abstraction:"rythme",consigne:"Un motif (son, geste, phrase) revient plusieurs fois dans la scÃ¨ne."},
  {categorie:"Regard",abstraction:"ambiance",consigne:"Les personnages Ã©vitent le regard les uns des autres."},
  {categorie:"Montre",abstraction:"temps",consigne:"Lâ€™horloge avance ou recule soudainement."},
  {categorie:"Songe",abstraction:"flou",consigne:"Le personnage principal ne sait plus sâ€™il rÃªve ou non."},
  {categorie:"Appel",abstraction:"Ã©vÃ©nement",consigne:"Un tÃ©lÃ©phone sonne, personne ne dÃ©croche."},
  {categorie:"DÃ©placement",abstraction:"action",consigne:"Les personnages changent brusquement de lieu."},
  {categorie:"Vitre",abstraction:"incident",consigne:"Une vitre se brise ou un miroir Ã©clate."},
  {categorie:"Secret",abstraction:"Ã©motion",consigne:"Un personnage rÃ©vÃ¨le Ã  voix basse un secret."},
  {categorie:"Fuite",abstraction:"action",consigne:"Quelquâ€™un prend soudain la fuite sans explication."},
  {categorie:"Solitude",abstraction:"psychologique",consigne:"Le personnage se sent totalement seul, mÃªme entourÃ©."},
  {categorie:"Musique",abstraction:"ambiance",consigne:"Un personnage fredonne une mÃ©lodie obsÃ©dante."},
  {categorie:"Erreur",abstraction:"structure",consigne:"Un mot ou un geste mal placÃ© dÃ©clenche une crise."},
  {categorie:"Flash",abstraction:"structure",consigne:"Un souvenir envahit la scÃ¨ne, en plein dialogue."},
  {categorie:"Parfum",abstraction:"sensoriel",consigne:"Une odeur forte envahit lâ€™air, sans origine Ã©vidente."},
  {categorie:"Ombre",abstraction:"dÃ©tail",consigne:"Une ombre Ã©trange se dessine sur le mur ou au sol."},
  {categorie:"Miroir",abstraction:"ambiance",consigne:"Le reflet dâ€™un personnage semble lui Ã©chapper."},
  {categorie:"Blessure",abstraction:"physique",consigne:"Un personnage se coupe, se cogne ou se brÃ»le accidentellement."},
  {categorie:"Objet perdu",abstraction:"incident",consigne:"Un objet indispensable manque au pire moment."},
  {categorie:"ClÃ©",abstraction:"dÃ©tail",consigne:"Un trousseau de clÃ©s disparaÃ®t mystÃ©rieusement."},
  {categorie:"Fatigue",abstraction:"psychologique",consigne:"Un personnage sâ€™endort contre sa volontÃ©."},
  {categorie:"Chanson",abstraction:"musique",consigne:"Un vieux tube passe Ã  la radio et trouble lâ€™ambiance."},
  {categorie:"Absence",abstraction:"structure",consigne:"Quelquâ€™un est attendu mais ne viendra jamais."},
  {categorie:"Peur",abstraction:"Ã©motion",consigne:"Le personnage a la chair de poule, sans comprendre pourquoi."},
  {categorie:"Bruit",abstraction:"ambiance",consigne:"Un bruit mÃ©canique ou naturel se rÃ©pÃ¨te, obsÃ©dant."},
  {categorie:"Tache",abstraction:"dÃ©tail",consigne:"Une tache Ã©trange apparaÃ®t sur les vÃªtements ou un mur."},
  {categorie:"Apparition",abstraction:"structure",consigne:"Quelquâ€™un ou quelque chose dâ€™inattendu entre en scÃ¨ne."},
  {categorie:"Lettre",abstraction:"objet",consigne:"Un personnage trouve ou reÃ§oit une lettre Ã©nigmatique."},
  {categorie:"Manque",abstraction:"Ã©motion",consigne:"Le hÃ©ros rÃ©alise quâ€™il nâ€™a plus faim, plus soif, ou plus envie de parler."},
  {categorie:"Suspicion",abstraction:"Ã©motion",consigne:"Un soupÃ§on sâ€™insinue sans preuve tangible."},
  {categorie:"Bruit sourd",abstraction:"ambiance",consigne:"Un grondement ou une vibration trouble lâ€™atmosphÃ¨re."},
  {categorie:"Erreur dâ€™identitÃ©",abstraction:"tension",consigne:"On confond un personnage avec un autre."},
  {categorie:"Blessure cachÃ©e",abstraction:"psychologique",consigne:"Un personnage masque une douleur."},
  {categorie:"Ã‰change de rÃ´les",abstraction:"structure",consigne:"Deux personnages changent de place ou de statut (physiquement ou symboliquement)."},
  {categorie:"Nourriture",abstraction:"dÃ©tail",consigne:"Un plat renversÃ© ou une boisson rÃ©pandue dÃ©clenche une tension."},
  {categorie:"Froid",abstraction:"ambiance",consigne:"La scÃ¨ne est glaciale, au propre ou au figurÃ©."},
  {categorie:"Renversement",abstraction:"structure",consigne:"Le plus faible devient soudain le plus fort."},
  {categorie:"Annonce",abstraction:"Ã©vÃ©nement",consigne:"Un message important est reÃ§u (oral, Ã©crit, SMS, etc.)."},
  {categorie:"Malaise",abstraction:"ambiance",consigne:"Quelquâ€™un tombe malade ou fait un malaise lÃ©ger."},
  {categorie:"Cris",abstraction:"son",consigne:"Un cri rÃ©sonne, sans que lâ€™on sache dâ€™oÃ¹ il vient."},
  {categorie:"Rupture",abstraction:"psychologique",consigne:"Un personnage rompt une relation ou un contrat."},
  {categorie:"Revoir",abstraction:"structure",consigne:"Un personnage croise quelquâ€™un quâ€™il nâ€™avait pas vu depuis longtemps."},
  {categorie:"Ã‰puisement",abstraction:"physique",consigne:"Un personnage agit de faÃ§on Ã©trange Ã  cause de la fatigue."},
  {categorie:"Chaleur",abstraction:"ambiance",consigne:"La scÃ¨ne est moite, suffocante, ou caniculaire."},
  {categorie:"Regret",abstraction:"psychologique",consigne:"Un personnage regrette un choix ou une parole, sans pouvoir revenir en arriÃ¨re."},
  {categorie:"Odeur",abstraction:"sensoriel",consigne:"Une odeur agrÃ©able ou repoussante modifie lâ€™atmosphÃ¨re."},
  {categorie:"GÃªne",abstraction:"ambiance",consigne:"Un silence gÃªnant sâ€™installe, personne nâ€™ose parler."},
  {categorie:"LumiÃ¨re",abstraction:"dÃ©tail",consigne:"Une lumiÃ¨re Ã©trange change lâ€™ambiance sans raison visible."},
  {categorie:"Changement mÃ©tÃ©o",abstraction:"structure",consigne:"Le temps change brusquement (pluie, neige, soleil, vent)."},
  {categorie:"Souvenir",abstraction:"psychologique",consigne:"Un personnage revoit une scÃ¨ne de son passÃ© en pleine action."},
  {categorie:"Faiblesse",abstraction:"Ã©motion",consigne:"Un personnage montre une faiblesse quâ€™il tente de cacher."},
  {categorie:"Perte de contrÃ´le",abstraction:"structure",consigne:"Quelquâ€™un perd totalement le contrÃ´le de ses Ã©motions ou de son corps."},
  {categorie:"Changement de dÃ©cor",abstraction:"structure",consigne:"La scÃ¨ne bascule dans un autre lieu, sans transition."},
  {categorie:"Gifle",abstraction:"action",consigne:"Un personnage gifle un autre (lÃ©gÃ¨rement ou violemment)."},
  {categorie:"Oublier",abstraction:"psychologique",consigne:"Un dÃ©tail essentiel est oubliÃ© par tous les personnages."},
  {categorie:"Tension",abstraction:"structure",consigne:"Le narrateur sent que la catastrophe est imminente, mais ne sait pas dâ€™oÃ¹ elle viendra."},
  {categorie:"Coupure de courant",abstraction:"Ã©vÃ©nement",consigne:"Tout sâ€™Ã©teint, la scÃ¨ne plonge dans lâ€™obscuritÃ©."},
  {categorie:"Doute",abstraction:"Ã©motion",consigne:"Un personnage doute de la version quâ€™on lui raconte."},
  {categorie:"Chute",abstraction:"structure",consigne:"Un personnage tombe, trÃ©buche, ou rate une marche Ã  un moment clÃ©."},
  {categorie:"Larme",abstraction:"Ã©motion",consigne:"Quelquâ€™un pleure, discrÃ¨tement ou bruyamment."},
  {categorie:"Rupture de ton",abstraction:"structure",consigne:"Le ton du rÃ©cit change brutalement (comique/triste, sÃ©rieux/absurde, etc.)."},
  {categorie:"Regard appuyÃ©",abstraction:"ambiance",consigne:"Un regard insistant met un personnage mal Ã  lâ€™aise."},
  {categorie:"Excuse",abstraction:"dialogue",consigne:"Un personnage invente une excuse absurde ou invraisemblable."},
  {categorie:"RÃ©pÃ©tition de mots",abstraction:"rythme",consigne:"Un mot ou une expression est rÃ©pÃ©tÃ© jusquâ€™Ã  lâ€™obsession."},
  {categorie:"Fracas",abstraction:"son",consigne:"Un bruit fracassant fait sursauter tout le monde."},
  {categorie:"Ã‰trangetÃ©",abstraction:"ambiance",consigne:"Quelque chose cloche dans la scÃ¨ne, sans que personne ne le formule."},
  {categorie:"Promesse",abstraction:"dialogue",consigne:"Une promesse est faite mais ne sera jamais tenue."},
  {categorie:"HÃ©sitation",abstraction:"psychologique",consigne:"Un personnage hÃ©site Ã  tout avouer mais se ravise."},
  {categorie:"Changement de rythme",abstraction:"structure",consigne:"La narration accÃ©lÃ¨re ou ralentit brusquement."},
  {categorie:"Objets",abstraction:"dÃ©tail",consigne:"Un objet minuscule prend soudain une importance capitale."},
  {categorie:"Accident",abstraction:"Ã©vÃ©nement",consigne:"Un personnage se blesse lÃ©gÃ¨rement (chute, brÃ»lure, coupureâ€¦)."},
  {categorie:"Erreur de jugement",abstraction:"structure",consigne:"Un personnage rÃ©alise quâ€™il sâ€™est trompÃ© sur quelquâ€™un."},
  {categorie:"Animaux",abstraction:"dÃ©tail",consigne:"La prÃ©sence ou lâ€™absence dâ€™un animal change lâ€™atmosphÃ¨re."},
  {categorie:"IncomprÃ©hension",abstraction:"dialogue",consigne:"Un quiproquo gÃ©nÃ¨re un conflit inattendu."},
  {categorie:"Retard",abstraction:"structure",consigne:"Un personnage arrive en retard et bouleverse les plans."},
  {categorie:"Peur du noir",abstraction:"Ã©motion",consigne:"La peur du noir ressurgit chez un personnage adulte."},
  {categorie:"Doute de soi",abstraction:"psychologique",consigne:"Un personnage nâ€™a plus confiance en lui le temps dâ€™une scÃ¨ne."},
  {categorie:"Affrontement",abstraction:"tension",consigne:"Deux personnages sâ€™affrontent en silence."},
  {categorie:"Musique forte",abstraction:"ambiance",consigne:"La musique couvre toutes les autres voix."},
  {categorie:"ExcÃ¨s",abstraction:"structure",consigne:"Quelquâ€™un en fait trop, Ã  en devenir ridicule ou inquiÃ©tant."},
  {categorie:"Souvenir dâ€™enfance",abstraction:"psychologique",consigne:"Un dÃ©tail du dÃ©cor rappelle lâ€™enfance dâ€™un personnage."},
  {categorie:"Pause",abstraction:"rythme",consigne:"Une scÃ¨ne de pause ou de transition permet de relÃ¢cher la tension."},
  {categorie:"Nuit blanche",abstraction:"structure",consigne:"Un personnage nâ€™a pas dormi de la nuit et tout vacille."},
  {categorie:"TempÃªte",abstraction:"mÃ©tÃ©o",consigne:"La mÃ©tÃ©o devient extrÃªme et enferme les personnages."},
  {categorie:"Message codÃ©",abstraction:"objet",consigne:"Un message cryptique est laissÃ© dans un lieu inattendu."},
  {categorie:"Jeu dâ€™enfants",abstraction:"ambiance",consigne:"Le rÃ©cit est ponctuÃ© par des bruits ou des souvenirs dâ€™enfants."},
  {categorie:"Habitude",abstraction:"structure",consigne:"Un personnage rompt avec une habitude tenace."},
  {categorie:"TÃ¢che impossible",abstraction:"action",consigne:"Un personnage sâ€™acharne sur une tÃ¢che manifestement vouÃ©e Ã  lâ€™Ã©chec."},
  {categorie:"Voix lointaine",abstraction:"son",consigne:"Une voix lointaine semble appeler un personnage."},
  {categorie:"Alcool fort",abstraction:"ambiance",consigne:"Un personnage boit trop, sa perception change."},
  {categorie:"TrÃ©sor",abstraction:"objet",consigne:"Un personnage trouve un trÃ©sor personnel, sans valeur pour les autres."},
  {categorie:"DÃ©lai",abstraction:"structure",consigne:"Quelque chose doit Ãªtre fait dans un temps trÃ¨s court."},
  {categorie:"Chiffre",abstraction:"dÃ©tail",consigne:"Un chiffre, une date ou un code hante la scÃ¨ne."},
  {categorie:"Bousculade",abstraction:"incident",consigne:"Un personnage bouscule involontairement un autre."},
  {categorie:"Regard furtif",abstraction:"dÃ©tail",consigne:"Un Ã©change de regards furtifs change lâ€™Ã©quilibre du groupe."},
  {categorie:"Erreur de nom",abstraction:"dialogue",consigne:"Quelquâ€™un se trompe de prÃ©nom ou de nom, provoquant la gÃªne."},
  {categorie:"Nostalgie",abstraction:"psychologique",consigne:"La nostalgie prend tout lâ€™espace, et paralyse lâ€™action."},
  {categorie:"Doute sur le temps",abstraction:"structure",consigne:"On ne sait plus quelle heure, quel jour, ou quelle annÃ©e on est."},
  {categorie:"RivalitÃ©",abstraction:"tension",consigne:"Deux personnages se disputent lâ€™attention dâ€™un tiers."},
  {categorie:"Feu",abstraction:"incident",consigne:"Un dÃ©but dâ€™incendie, mÃªme minime, inquiÃ¨te tout le monde."},
  {categorie:"PoignÃ©e de main",abstraction:"dÃ©tail",consigne:"Une poignÃ©e de main est refusÃ©e ou trop appuyÃ©e."},
  {categorie:"Fatigue extrÃªme",abstraction:"physique",consigne:"Un personnage sâ€™endort debout, ou parle en dormant."},
  {categorie:"Peur du ridicule",abstraction:"psychologique",consigne:"Un personnage a honte dâ€™une erreur passÃ©e."},
  {categorie:"Pluie battante",abstraction:"mÃ©tÃ©o",consigne:"Une pluie diluvienne isole les personnages du reste du monde."},
  {categorie:"Coup de fil interrompu",abstraction:"structure",consigne:"Une conversation tÃ©lÃ©phonique est brutalement interrompue."},
  {categorie:"Toux",abstraction:"physique",consigne:"Un personnage tousse au point dâ€™alerter les autres."},
  {categorie:"Trouble de mÃ©moire",abstraction:"psychologique",consigne:"Un personnage nâ€™arrive plus Ã  se souvenir dâ€™un dÃ©tail essentiel."},
  {categorie:"ArrivÃ©e tardive",abstraction:"structure",consigne:"Un personnage important arrive Ã  la fin dâ€™une scÃ¨ne clÃ©."},
  {categorie:"Blague",abstraction:"dialogue",consigne:"Quelquâ€™un tente une blague, et lâ€™ambiance se tend."},
  {categorie:"Choc thermique",abstraction:"dÃ©tail",consigne:"Un personnage passe brutalement du chaud au froid."},
  {categorie:"Surprise ratÃ©e",abstraction:"structure",consigne:"Une surprise est dÃ©voilÃ©e trop tÃ´t."},
  {categorie:"Fausse accusation",abstraction:"tension",consigne:"Un personnage accuse Ã  tort un autre dâ€™un vol, dâ€™un mensonge ou dâ€™une trahison."},
  {categorie:"Souvenir tactile",abstraction:"sensoriel",consigne:"Le contact dâ€™une matiÃ¨re ramÃ¨ne le hÃ©ros Ã  un Ã©vÃ©nement passÃ©."},
  {categorie:"Odeur de brÃ»lÃ©",abstraction:"sensoriel",consigne:"Tout le monde sent une odeur suspecte."},
  {categorie:"Grincement",abstraction:"son",consigne:"Un bruit mÃ©tallique ou sinistre agace ou effraie les personnages."},
  {categorie:"Crise de rire",abstraction:"psychologique",consigne:"Un fou rire incontrÃ´lable Ã©clate Ã  un moment inopportun."},
  {categorie:"Gratitude inattendue",abstraction:"Ã©motion",consigne:"Un personnage remercie un autre de faÃ§on excessive ou dÃ©placÃ©e."},
  {categorie:"Ã‰change de vÃªtements",abstraction:"structure",consigne:"Deux personnages Ã©changent dâ€™habits ou accessoires, pour tromper quelquâ€™un."},
  {categorie:"Photo abÃ®mÃ©e",abstraction:"objet",consigne:"Une vieille photo est retrouvÃ©e, dÃ©chirÃ©e ou tÃ¢chÃ©e."},
  {categorie:"Message vocal",abstraction:"structure",consigne:"Un message vocal mal compris dÃ©clenche une action."},
  {categorie:"Jeu de regard",abstraction:"tension",consigne:"Un personnage dÃ©visage un autre, sans raison claire."},
  {categorie:"Erreur de porte",abstraction:"structure",consigne:"Un personnage entre dans la mauvaise piÃ¨ce ou le mauvais lieu."},
  {categorie:"Manque dâ€™argent",abstraction:"tension",consigne:"La question dâ€™argent devient un problÃ¨me central, mÃªme briÃ¨vement."},
  {categorie:"Fausse piste",abstraction:"structure",consigne:"On suit un dÃ©tail ou une rumeur qui ne mÃ¨ne Ã  rien."},
  {categorie:"Honte",abstraction:"Ã©motion",consigne:"Un personnage a honte dâ€™une action rÃ©cente."},
  {categorie:"Rangement",abstraction:"action",consigne:"Quelquâ€™un range frÃ©nÃ©tiquement, rÃ©vÃ©lant un trouble intÃ©rieur."},
  {categorie:"Portes qui claquent",abstraction:"son",consigne:"Des portes claquent, volontairement ou par accident, modifiant la tension."},
  {categorie:"Traces",abstraction:"dÃ©tail",consigne:"Des traces (boue, sang, peintureâ€¦) perturbent les personnages."},
  {categorie:"DÃ©sorientation",abstraction:"psychologique",consigne:"Personne ne sait vraiment oÃ¹ il est, ou comment il est arrivÃ© lÃ ."},
  {categorie:"Fausse dÃ©claration",abstraction:"structure",consigne:"Un personnage fait une dÃ©claration solennelle mais fausse."},
  {categorie:"Douche froide",abstraction:"dÃ©tail",consigne:"Un Ã©vÃ©nement coupe court Ã  lâ€™enthousiasme gÃ©nÃ©ral."},
  {categorie:"RÃªve Ã©veillÃ©",abstraction:"psychologique",consigne:"Le hÃ©ros croit rÃªver alors que tout est rÃ©el."},
  {categorie:"Mains sales",abstraction:"dÃ©tail",consigne:"Un personnage remarque que ses mains sont sales ou blessÃ©es."},
  {categorie:"Odeur de tabac",abstraction:"sensoriel",consigne:"Lâ€™odeur du tabac ou dâ€™une cigarette trouble la scÃ¨ne."},
  {categorie:"Proposition absurde",abstraction:"dialogue",consigne:"Un personnage propose quelque chose dâ€™irrÃ©aliste ou dâ€™impossible."},
  {categorie:"FenÃªtre ouverte",abstraction:"dÃ©tail",consigne:"Le vent sâ€™engouffre par une fenÃªtre restÃ©e ouverte."},
  {categorie:"Choc du passÃ©",abstraction:"psychologique",consigne:"Le retour dâ€™un personnage ancien trouble lâ€™Ã©quilibre du groupe."},
  {categorie:"Mensonge flagrant",abstraction:"tension",consigne:"Un personnage ment effrontÃ©ment et personne ne le relÃ¨ve."},
  {categorie:"Ã‰pice",abstraction:"sensoriel",consigne:"Un plat trop Ã©picÃ© dÃ©clenche une mini-crise."},
  {categorie:"Regard dans le vide",abstraction:"psychologique",consigne:"Un personnage fixe le vide, absent ou inquiet."},
  {categorie:"Changement de plan",abstraction:"structure",consigne:"Le plan initial est abandonnÃ© sur un coup de tÃªte."},
  {categorie:"Refus",abstraction:"structure",consigne:"Un personnage refuse catÃ©goriquement une demande banale."},
  {categorie:"Ã‰change de sacs",abstraction:"incident",consigne:"Des sacs sont Ã©changÃ©s, volontairement ou non, et brouillent la suite."},
  {categorie:"Souvenir olfactif",abstraction:"sensoriel",consigne:"Une odeur ramÃ¨ne brutalement un souvenir dâ€™enfance ou dâ€™amour."},
  {categorie:"Coupure dâ€™eau",abstraction:"incident",consigne:"Lâ€™eau sâ€™arrÃªte au pire moment."},
  {categorie:"Objet fÃ©tiche perdu",abstraction:"objet",consigne:"Un personnage perd un objet quâ€™il considÃ¨re porte-bonheur."},
  {categorie:"Erreur dâ€™itinÃ©raire",abstraction:"structure",consigne:"Un personnage se perd, ou fait semblant de se perdre."},
  {categorie:"Regard de dÃ©fi",abstraction:"tension",consigne:"Un Ã©change de regards marque le dÃ©but dâ€™une rivalitÃ©."},
  {categorie:"Cauchemar",abstraction:"psychologique",consigne:"Un personnage se rÃ©veille en sursaut dâ€™un rÃªve effrayant."},
  {categorie:"DÃ©masquage",abstraction:"structure",consigne:"Un secret ou une identitÃ© cachÃ©e Ã©clate soudainement."},
  {categorie:"Panique",abstraction:"action",consigne:"La panique se propage sans cause Ã©vidente."},
  {categorie:"Manque dâ€™air",abstraction:"physique",consigne:"Un personnage suffoque, par peur ou pour de vrai."},
  {categorie:"Tension sexuelle",abstraction:"ambiance",consigne:"Une tension Ã©rotique sous-jacente trouble la scÃ¨ne."},
  {categorie:"BrÃ»lure du regard",abstraction:"dÃ©tail",consigne:"Un regard intense en dit plus que mille mots."},
  {categorie:"Douleur refoulÃ©e",abstraction:"psychologique",consigne:"Un personnage tente de cacher une douleur profonde."},
  {categorie:"Effondrement",abstraction:"action",consigne:"Un personnage sâ€™effondre, physiquement ou moralement."},
  {categorie:"Geste manquÃ©",abstraction:"structure",consigne:"Quelquâ€™un manque un geste important Ã  cause du stress."},
  {categorie:"Explosion",abstraction:"Ã©vÃ©nement",consigne:"Quelque chose explose ou se casse de faÃ§on inattendue."},
  {categorie:"Fausse confession",abstraction:"structure",consigne:"Un personnage ment lors dâ€™une confession supposÃ©e sincÃ¨re."},
  {categorie:"Confusion des prÃ©noms",abstraction:"dÃ©tail",consigne:"Un personnage est appelÃ© par un autre prÃ©nom."},
  {categorie:"Cauchemar Ã©veillÃ©",abstraction:"psychologique",consigne:"Un Ã©lÃ©ment de cauchemar sâ€™invite dans la rÃ©alitÃ©."},
  {categorie:"Disparition soudaine",abstraction:"structure",consigne:"Un personnage quitte la scÃ¨ne sans prÃ©venir."},
  {categorie:"Rumeur",abstraction:"structure",consigne:"Une rumeur se rÃ©pand et influence la scÃ¨ne."},
  {categorie:"Absence de rÃ©action",abstraction:"psychologique",consigne:"Un personnage reste de marbre malgrÃ© lâ€™Ã©motion ambiante."},
  {categorie:"Rappel Ã  lâ€™ordre",abstraction:"dialogue",consigne:"Quelquâ€™un rappelle la rÃ¨gle ou lâ€™ordre oubliÃ© de tous."},
  {categorie:"Choc des gÃ©nÃ©rations",abstraction:"structure",consigne:"Deux gÃ©nÃ©rations sâ€™opposent frontalement."},
  {categorie:"Retard",abstraction:"structure",consigne:"Quelquâ€™un arrive en retard, bouleversant lâ€™organisation."},
  {categorie:"Cadeau empoisonnÃ©",abstraction:"structure",consigne:"Un cadeau inattendu complique la situation."},
  {categorie:"Jet de liquide",abstraction:"action",consigne:"Un liquide est jetÃ©, renversÃ©, ou Ã©clabousse involontairement."},
  {categorie:"Doute sur le passÃ©",abstraction:"psychologique",consigne:"Le personnage doute de ses propres souvenirs."},
  {categorie:"ColÃ¨re froide",abstraction:"Ã©motion",consigne:"Un personnage exprime sa colÃ¨re par des gestes retenus."},
  {categorie:"Sursaut collectif",abstraction:"structure",consigne:"Plusieurs personnages rÃ©agissent en mÃªme temps Ã  un Ã©vÃ©nement."},
  {categorie:"Longue lettre",abstraction:"objet",consigne:"Un personnage Ã©crit ou reÃ§oit une lettre interminable."},
  {categorie:"Fausse alerte",abstraction:"structure",consigne:"Une fausse alerte provoque lâ€™agitation."},
  {categorie:"Rituel absurde",abstraction:"structure",consigne:"Un rituel ou une routine Ã©trange sâ€™installe."},
  {categorie:"Plaisanterie dÃ©placÃ©e",abstraction:"dialogue",consigne:"Une blague mal placÃ©e dÃ©clenche un malaise."},
  {categorie:"Oubli volontaire",abstraction:"psychologique",consigne:"Un personnage feint dâ€™avoir oubliÃ© un fait crucial."},
  {categorie:"Changement de langue",abstraction:"dialogue",consigne:"Un personnage change brusquement de langue."},
  {categorie:"Geste de tendresse",abstraction:"action",consigne:"Un geste inattendu dâ€™affection dÃ©stabilise la scÃ¨ne."},
  {categorie:"Faible luminositÃ©",abstraction:"ambiance",consigne:"Tout se joue dans la pÃ©nombre ou lâ€™obscuritÃ©."},
  {categorie:"Plaie ouverte",abstraction:"dÃ©tail",consigne:"Un personnage montre ou cache une plaie rÃ©cente."},
  {categorie:"RÃ©pÃ©tition dâ€™un rÃªve",abstraction:"psychologique",consigne:"Un rÃªve ou cauchemar rÃ©current perturbe la narration."},
  {categorie:"Jeu de mains",abstraction:"action",consigne:"Un jeu de mains (bague, piÃ¨ce, briquetâ€¦) trahit lâ€™Ã©tat dâ€™esprit dâ€™un personnage."},
  {categorie:"MontÃ©e de fiÃ¨vre",abstraction:"physique",consigne:"Un personnage est pris dâ€™une fiÃ¨vre soudaine."},
  {categorie:"Objet brisÃ©",abstraction:"dÃ©tail",consigne:"Un objet symbolique se brise au pire moment."},
  {categorie:"Main tendue",abstraction:"action",consigne:"Un personnage propose son aide contre toute attente."},
  {categorie:"DÃ©tail dÃ©placÃ©",abstraction:"dÃ©tail",consigne:"Un Ã©lÃ©ment du dÃ©cor nâ€™a rien Ã  faire lÃ ."},
  {categorie:"Fausse identitÃ©",abstraction:"structure",consigne:"Un personnage se fait passer pour un autre."},
  {categorie:"Vibration",abstraction:"son",consigne:"Une vibration (tÃ©lÃ©phone, machineâ€¦) trouble le silence."},
  {categorie:"Silence assourdissant",abstraction:"ambiance",consigne:"Le silence devient pesant, jusquâ€™Ã  rendre tout dialogue impossible."},
  {categorie:"DÃ©ni",abstraction:"psychologique",consigne:"Un personnage refuse dâ€™admettre une Ã©vidence."},
  {categorie:"Dernier mot",abstraction:"dialogue",consigne:"Un personnage impose le dernier mot, Ã  tout prix."},
  {categorie:"Dispute",abstraction:"action",consigne:"Un conflit Ã©clate et emporte tous les personnages."},
  {categorie:"DÃ©placement de mobilier",abstraction:"action",consigne:"Un meuble ou un objet lourd est dÃ©placÃ©, rÃ©vÃ©lant un secret."},
  {categorie:"Lapsus rÃ©vÃ©lateur",abstraction:"dialogue",consigne:"Un lapsus change la tournure de la scÃ¨ne."},
  {categorie:"Suspense prolongÃ©",abstraction:"structure",consigne:"On fait durer le suspense jusquâ€™Ã  lâ€™absurde."},
  {categorie:"Apparition inopinÃ©e",abstraction:"structure",consigne:"Un personnage entre en scÃ¨ne sans logique apparente."},
  {categorie:"Oubli de rendez-vous",abstraction:"structure",consigne:"Un rendez-vous important est oubliÃ© ou ratÃ©."},
  {categorie:"Doute existentiel",abstraction:"psychologique",consigne:"Un personnage remet en cause toute son existence."},
  {categorie:"Chaleur Ã©touffante",abstraction:"ambiance",consigne:"La chaleur pÃ¨se sur les corps et les esprits."},
  {categorie:"Voix off intrusive",abstraction:"structure",consigne:"Une voix intÃ©rieure interrompt le dÃ©roulement de la scÃ¨ne."},
  {categorie:"Retour du passÃ©",abstraction:"structure",consigne:"Un Ã©lÃ©ment du passÃ© fait irruption dans le prÃ©sent."},
  {categorie:"Changement brutal de dÃ©cor",abstraction:"structure",consigne:"Tout bascule, le lieu ou le temps change dâ€™un coup."},
  {categorie:"DÃ©goÃ»t",abstraction:"Ã©motion",consigne:"Un personnage est pris de dÃ©goÃ»t pour un lieu, une personne, ou lui-mÃªme."},
  {categorie:"Marque corporelle",abstraction:"dÃ©tail",consigne:"Une marque (grain de beautÃ©, tatouage, cicatrice) prend un sens nouveau."},
  {categorie:"Invitation refusÃ©e",abstraction:"dialogue",consigne:"Un personnage dÃ©cline une invitation ou un ordre avec force."},
  {categorie:"Crise de panique",abstraction:"psychologique",consigne:"Un personnage panique, entraÃ®nant les autres dans sa spirale."},
  {categorie:"RÃ©action inattendue",abstraction:"structure",consigne:"Un personnage rÃ©agit Ã  contre-emploi (rires face au danger, calme face au chaosâ€¦)."},
  {categorie:"Fausse mort",abstraction:"structure",consigne:"Quelquâ€™un fait croire Ã  sa propre mort ou celle dâ€™un autre."},
  {categorie:"Obstacle inattendu",abstraction:"structure",consigne:"Un obstacle imprÃ©vu change tout le dÃ©roulÃ© de la scÃ¨ne."},
  {categorie:"Honte",abstraction:"Ã©motion",consigne:"Un personnage Ã©prouve de la honte pour lui ou un autre."},
  {categorie:"Ã‰puisement collectif",abstraction:"ambiance",consigne:"Tous les personnages sont au bout de leurs forces."},
  {categorie:"Garde du secret",abstraction:"structure",consigne:"Un personnage dÃ©cide de ne jamais rÃ©vÃ©ler ce quâ€™il sait."},
  {categorie:"Objets qui tombent",abstraction:"action",consigne:"Des objets tombent ou sâ€™effondrent, sans explication claire."},
  {categorie:"Refus du dialogue",abstraction:"dialogue",consigne:"Un personnage se mure dans le silence face Ã  toute tentative de discussion."},
  {categorie:"Imitation",abstraction:"action",consigne:"Un personnage imite ou parodie un autre, volontairement ou non."},
  {categorie:"Souvenir douloureux",abstraction:"psychologique",consigne:"Un souvenir douloureux ressurgit, bouleversant la scÃ¨ne."},
  {categorie:"DÃ©rive",abstraction:"structure",consigne:"La scÃ¨ne sâ€™Ã©loigne complÃ¨tement de son objectif initial."},
  {categorie:"Contact physique",abstraction:"action",consigne:"Un contact physique inattendu provoque un Ã©lectrochoc."},
  {categorie:"Personnage inattendu",abstraction:"MÃ©tamorphose interne",consigne:"Explore lâ€™idÃ©e de Â« MÃ©tamorphose interne Â» dans un contexte inattendu : quel impact sur l'intrigue ?"},
  {categorie:"Personnage inattendu",abstraction:"Double identitÃ©",consigne:"Explore lâ€™idÃ©e de Â« Double identitÃ© Â» dans un contexte inattendu : quel impact sur l'intrigue ?"},
  {categorie:"Personnage inattendu",abstraction:"RÃ´le inversÃ©",consigne:"Explore lâ€™idÃ©e de Â« RÃ´le inversÃ© Â» dans un contexte inattendu : quel impact sur l'intrigue ?"},
  {categorie:"Personnage inattendu",abstraction:"Secret rÃ©vÃ©lÃ©",consigne:"Explore lâ€™idÃ©e de Â« Secret rÃ©vÃ©lÃ© Â» dans un contexte inattendu : quel impact sur l'intrigue ?"},
  {categorie:"Personnage inattendu",abstraction:"Voix intÃ©rieure",consigne:"Explore lâ€™idÃ©e de Â« Voix intÃ©rieure Â» dans un contexte inattendu : quel impact sur l'intrigue ?"},
  {categorie:"DÃ©cor / Monde",abstraction:"Lieu chargÃ© dâ€™histoire",consigne:"Explore lâ€™idÃ©e de Â« Lieu chargÃ© dâ€™histoire Â» dans un contexte inattendu : quel impact sur l'intrigue ?"},
  {categorie:"DÃ©cor / Monde",abstraction:"Ã‰lÃ©ment perturbateur",consigne:"Explore lâ€™idÃ©e de Â« Ã‰lÃ©ment perturbateur Â» dans un contexte inattendu : quel impact sur l'intrigue ?"},
  {categorie:"DÃ©cor / Monde",abstraction:"Ancrage temporel",consigne:"Explore lâ€™idÃ©e de Â« Ancrage temporel Â» dans un contexte inattendu : quel impact sur l'intrigue ?"},
  {categorie:"DÃ©cor / Monde",abstraction:"Miroir dÃ©formant",consigne:"Explore lâ€™idÃ©e de Â« Miroir dÃ©formant Â» dans un contexte inattendu : quel impact sur l'intrigue ?"},
  {categorie:"DÃ©cor / Monde",abstraction:"SymÃ©trie parfaite",consigne:"Explore lâ€™idÃ©e de Â« SymÃ©trie parfaite Â» dans un contexte inattendu : quel impact sur l'intrigue ?"},
  {categorie:"Conflit & tension",abstraction:"Ultimatum",consigne:"Explore lâ€™idÃ©e de Â« Ultimatum Â» dans un contexte inattendu : quel impact sur l'intrigue ?"},
  {categorie:"Conflit & tension",abstraction:"Dilemme moral",consigne:"Explore lâ€™idÃ©e de Â« Dilemme moral Â» dans un contexte inattendu : quel impact sur l'intrigue ?"},
  {categorie:"Conflit & tension",abstraction:"Trahison latente",consigne:"Explore lâ€™idÃ©e de Â« Trahison latente Â» dans un contexte inattendu : quel impact sur l'intrigue ?"},
  {categorie:"Conflit & tension",abstraction:"Course contre la montre",consigne:"Explore lâ€™idÃ©e de Â« Course contre la montre Â» dans un contexte inattendu : quel impact sur l'intrigue ?"},
  {categorie:"Conflit & tension",abstraction:"Jeu de dupes",consigne:"Explore lâ€™idÃ©e de Â« Jeu de dupes Â» dans un contexte inattendu : quel impact sur l'intrigue ?"},
  {categorie:"Ã‰motion / IntÃ©rieur",abstraction:"Ã‰cho Ã©motionnel",consigne:"Explore lâ€™idÃ©e de Â« Ã‰cho Ã©motionnel Â» dans un contexte inattendu : quel impact sur l'intrigue ?"},
  {categorie:"Ã‰motion / IntÃ©rieur",abstraction:"Blocage sensoriel",consigne:"Explore lâ€™idÃ©e de Â« Blocage sensoriel Â» dans un contexte inattendu : quel impact sur l'intrigue ?"},
  {categorie:"Ã‰motion / IntÃ©rieur",abstraction:"MÃ©moire sÃ©lective",consigne:"Explore lâ€™idÃ©e de Â« MÃ©moire sÃ©lective Â» dans un contexte inattendu : quel impact sur l'intrigue ?"},
  {categorie:"Ã‰motion / IntÃ©rieur",abstraction:"Rituel intime",consigne:"Explore lâ€™idÃ©e de Â« Rituel intime Â» dans un contexte inattendu : quel impact sur l'intrigue ?"},
  {categorie:"Ã‰motion / IntÃ©rieur",abstraction:"Masque social",consigne:"Explore lâ€™idÃ©e de Â« Masque social Â» dans un contexte inattendu : quel impact sur l'intrigue ?"},
  {categorie:"Relation / Rencontre",abstraction:"Correspondance muette",consigne:"Explore lâ€™idÃ©e de Â« Correspondance muette Â» dans un contexte inattendu : quel impact sur l'intrigue ?"},
  {categorie:"Relation / Rencontre",abstraction:"Rencontre hors-temps",consigne:"Explore lâ€™idÃ©e de Â« Rencontre hors-temps Â» dans un contexte inattendu : quel impact sur l'intrigue ?"},
  {categorie:"Relation / Rencontre",abstraction:"Alliance improbable",consigne:"Explore lâ€™idÃ©e de Â« Alliance improbable Â» dans un contexte inattendu : quel impact sur l'intrigue ?"},
  {categorie:"Relation / Rencontre",abstraction:"Faux-semblant",consigne:"Explore lâ€™idÃ©e de Â« Faux-semblant Â» dans un contexte inattendu : quel impact sur l'intrigue ?"},
  {categorie:"Relation / Rencontre",abstraction:"Symbiose forcÃ©e",consigne:"Explore lâ€™idÃ©e de Â« Symbiose forcÃ©e Â» dans un contexte inattendu : quel impact sur l'intrigue ?"},
  {categorie:"Objet catalyseur",abstraction:"Objet souvenir",consigne:"Explore lâ€™idÃ©e de Â« Objet souvenir Â» dans un contexte inattendu : quel impact sur l'intrigue ?"},
  {categorie:"Objet catalyseur",abstraction:"Artefact anachronique",consigne:"Explore lâ€™idÃ©e de Â« Artefact anachronique Â» dans un contexte inattendu : quel impact sur l'intrigue ?"},
  {categorie:"Objet catalyseur",abstraction:"ClÃ© mystÃ©rieuse",consigne:"Explore lâ€™idÃ©e de Â« ClÃ© mystÃ©rieuse Â» dans un contexte inattendu : quel impact sur l'intrigue ?"},
  {categorie:"Objet catalyseur",abstraction:"Miroir dÃ©formant",consigne:"Explore lâ€™idÃ©e de Â« Miroir dÃ©formant Â» dans un contexte inattendu : quel impact sur l'intrigue ?"},
  {categorie:"Objet catalyseur",abstraction:"Lettre posthume",consigne:"Explore lâ€™idÃ©e de Â« Lettre posthume Â» dans un contexte inattendu : quel impact sur l'intrigue ?"},
  {categorie:"Question ouverte",abstraction:"Et siâ€¦",consigne:"Explore lâ€™idÃ©e de Â« Et siâ€¦ Â» dans un contexte inattendu : quel impact sur l'intrigue ?"},
  {categorie:"Question ouverte",abstraction:"Point de bascule",consigne:"Explore lâ€™idÃ©e de Â« Point de bascule Â» dans un contexte inattendu : quel impact sur l'intrigue ?"},
  {categorie:"Question ouverte",abstraction:"Monde inversÃ©",consigne:"Explore lâ€™idÃ©e de Â« Monde inversÃ© Â» dans un contexte inattendu : quel impact sur l'intrigue ?"},
  {categorie:"Question ouverte",abstraction:"RÃ©vÃ©lation globale",consigne:"Explore lâ€™idÃ©e de Â« RÃ©vÃ©lation globale Â» dans un contexte inattendu : quel impact sur l'intrigue ?"},
  {categorie:"Question ouverte",abstraction:"Silence absolu",consigne:"Explore lâ€™idÃ©e de Â« Silence absolu Â» dans un contexte inattendu : quel impact sur l'intrigue ?"},
  {categorie:"Contrainte formelle",abstraction:"RÃ©pÃ©tition",consigne:"Explore lâ€™idÃ©e de Â« RÃ©pÃ©tition Â» dans un contexte inattendu : quel impact sur l'intrigue ?"},
  {categorie:"Contrainte formelle",abstraction:"Chapitre inversÃ©",consigne:"Explore lâ€™idÃ©e de Â« Chapitre inversÃ© Â» dans un contexte inattendu : quel impact sur l'intrigue ?"},
  {categorie:"Contrainte formelle",abstraction:"Temps restreint",consigne:"Explore lâ€™idÃ©e de Â« Temps restreint Â» dans un contexte inattendu : quel impact sur l'intrigue ?"},
  {categorie:"Contrainte formelle",abstraction:"Monologue intÃ©rieur",consigne:"Explore lâ€™idÃ©e de Â« Monologue intÃ©rieur Â» dans un contexte inattendu : quel impact sur l'intrigue ?"},
  {categorie:"Contrainte formelle",abstraction:"Narrateur non fiable",consigne:"Explore lâ€™idÃ©e de Â« Narrateur non fiable Â» dans un contexte inattendu : quel impact sur l'intrigue ?"},
  {categorie:"ThÃ¨me universel",abstraction:"QuÃªte de sens",consigne:"Explore lâ€™idÃ©e de Â« QuÃªte de sens Â» dans un contexte inattendu : quel impact sur l'intrigue ?"},
  {categorie:"ThÃ¨me universel",abstraction:"Pouvoir & responsabilitÃ©",consigne:"Explore lâ€™idÃ©e de Â« Pouvoir & responsabilitÃ© Â» dans un contexte inattendu : quel impact sur l'intrigue ?"},
  {categorie:"ThÃ¨me universel",abstraction:"RÃ©demption",consigne:"Explore lâ€™idÃ©e de Â« RÃ©demption Â» dans un contexte inattendu : quel impact sur l'intrigue ?"},
  {categorie:"ThÃ¨me universel",abstraction:"Mort symbolique",consigne:"Explore lâ€™idÃ©e de Â« Mort symbolique Â» dans un contexte inattendu : quel impact sur l'intrigue ?"},
  {categorie:"ThÃ¨me universel",abstraction:"Naissance inattendue",consigne:"Explore lâ€™idÃ©e de Â« Naissance inattendue Â» dans un contexte inattendu : quel impact sur l'intrigue ?"},
  {categorie:"Chute / Twist",abstraction:"Perspective renversÃ©e",consigne:"Explore lâ€™idÃ©e de Â« Perspective renversÃ©e Â» dans un contexte inattendu : quel impact sur l'intrigue ?"},
  {categorie:"Chute / Twist",abstraction:"VÃ©ritÃ© fragmentÃ©e",consigne:"Explore lâ€™idÃ©e de Â« VÃ©ritÃ© fragmentÃ©e Â» dans un contexte inattendu : quel impact sur l'intrigue ?"},
  {categorie:"Chute / Twist",abstraction:"Ruse finale",consigne:"Explore lâ€™idÃ©e de Â« Ruse finale Â» dans un contexte inattendu : quel impact sur l'intrigue ?"},
  {categorie:"Chute / Twist",abstraction:"Retour en trompe-lâ€™Å“il",consigne:"Explore lâ€™idÃ©e de Â« Retour en trompe-lâ€™Å“il Â» dans un contexte inattendu : quel impact sur l'intrigue ?"},
  {categorie:"Chute / Twist",abstraction:"Masque levÃ©",consigne:"Explore lâ€™idÃ©e de Â« Masque levÃ© Â» dans un contexte inattendu : quel impact sur l'intrigue ?"},
  {categorie:"Personnage inattendu",abstraction:"MÃ©tamorphose interne",consigne:"Explore lâ€™idÃ©e de Â« MÃ©tamorphose interne Â» dans un contexte surrÃ©aliste : quel impact sur l'intrigue ?"},
  {categorie:"Personnage inattendu",abstraction:"MÃ©tamorphose interne",consigne:"Explore lâ€™idÃ©e de Â« MÃ©tamorphose interne Â» dans un contexte mystÃ©rieux : quel impact sur l'intrigue ?"},
  {categorie:"Personnage inattendu",abstraction:"MÃ©tamorphose interne",consigne:"Explore lâ€™idÃ©e de Â« MÃ©tamorphose interne Â» dans un contexte dramatique : quel impact sur l'intrigue ?"},
  {categorie:"Personnage inattendu",abstraction:"MÃ©tamorphose interne",consigne:"Explore lâ€™idÃ©e de Â« MÃ©tamorphose interne Â» dans un contexte surrÃ©aliste : quel impact sur l'intrigue ?"},
  {categorie:"Personnage inattendu",abstraction:"MÃ©tamorphose interne",consigne:"Explore lâ€™idÃ©e de Â« MÃ©tamorphose interne Â» dans un contexte mystÃ©rieux : quel impact sur l'intrigue ?"},
  {categorie:"Personnage inattendu",abstraction:"MÃ©tamorphose interne",consigne:"Explore lâ€™idÃ©e de Â« MÃ©tamorphose interne Â» dans un contexte dramatique : quel impact sur l'intrigue ?"},
  {categorie:"Personnage inattendu",abstraction:"MÃ©tamorphose interne",consigne:"Explore lâ€™idÃ©e de Â« MÃ©tamorphose interne Â» dans un contexte surrÃ©aliste : quel impact sur l'intrigue ?"},
  {categorie:"Personnage inattendu",abstraction:"MÃ©tamorphose interne",consigne:"Explore lâ€™idÃ©e de Â« MÃ©tamorphose interne Â» dans un contexte mystÃ©rieux : quel impact sur l'intrigue ?"},
  {categorie:"Personnage inattendu",abstraction:"MÃ©tamorphose interne",consigne:"Explore lâ€™idÃ©e de Â« MÃ©tamorphose interne Â» dans un contexte dramatique : quel impact sur l'intrigue ?"},
  {categorie:"Personnage inattendu",abstraction:"MÃ©tamorphose interne",consigne:"Explore lâ€™idÃ©e de Â« MÃ©tamorphose interne Â» dans un contexte surrÃ©aliste : quel impact sur l'intrigue ?"},
  {categorie:"Personnage inattendu",abstraction:"MÃ©tamorphose interne",consigne:"Explore lâ€™idÃ©e de Â« MÃ©tamorphose interne Â» dans un contexte mystÃ©rieux : quel impact sur l'intrigue ?"},
  {categorie:"Personnage inattendu",abstraction:"MÃ©tamorphose interne",consigne:"Explore lâ€™idÃ©e de Â« MÃ©tamorphose interne Â» dans un contexte dramatique : quel impact sur l'intrigue ?"},
  {categorie:"Personnage inattendu",abstraction:"MÃ©tamorphose interne",consigne:"Explore lâ€™idÃ©e de Â« MÃ©tamorphose interne Â» dans un contexte surrÃ©aliste : quel impact sur l'intrigue ?"},
  {categorie:"Personnage inattendu",abstraction:"MÃ©tamorphose interne",consigne:"Explore lâ€™idÃ©e de Â« MÃ©tamorphose interne Â» dans un contexte mystÃ©rieux : quel impact sur l'intrigue ?"},
  {categorie:"Personnage inattendu",abstraction:"MÃ©tamorphose interne",consigne:"Explore lâ€™idÃ©e de Â« MÃ©tamorphose interne Â» dans un contexte dramatique : quel impact sur l'intrigue ?"},
  {categorie:"Personnage inattendu",abstraction:"MÃ©tamorphose interne",consigne:"Explore lâ€™idÃ©e de Â« MÃ©tamorphose interne Â» dans un contexte surrÃ©aliste : quel impact sur l'intrigue ?"},
  {categorie:"Personnage inattendu",abstraction:"MÃ©tamorphose interne",consigne:"Explore lâ€™idÃ©e de Â« MÃ©tamorphose interne Â» dans un contexte mystÃ©rieux : quel impact sur l'intrigue ?"},
  {categorie:"Personnage inattendu",abstraction:"MÃ©tamorphose interne",consigne:"Explore lâ€™idÃ©e de Â« MÃ©tamorphose interne Â» dans un contexte dramatique : quel impact sur l'intrigue ?"},
  {categorie:"Personnage inattendu",abstraction:"MÃ©tamorphose interne",consigne:"Explore lâ€™idÃ©e de Â« MÃ©tamorphose interne Â» dans un contexte surrÃ©aliste : quel impact sur l'intrigue ?"},
  {categorie:"Personnage inattendu",abstraction:"MÃ©tamorphose interne",consigne:"Explore lâ€™idÃ©e de Â« MÃ©tamorphose interne Â» dans un contexte mystÃ©rieux : quel impact sur l'intrigue ?"},
  {categorie:"Personnage inattendu",abstraction:"MÃ©tamorphose interne",consigne:"Explore lâ€™idÃ©e de Â« MÃ©tamorphose interne Â» dans un contexte dramatique : quel impact sur l'intrigue ?"},
  {categorie:"Personnage inattendu",abstraction:"MÃ©tamorphose interne",consigne:"Explore lâ€™idÃ©e de Â« MÃ©tamorphose interne Â» dans un contexte surrÃ©aliste : quel impact sur l'intrigue ?"},
  {categorie:"Personnage inattendu",abstraction:"MÃ©tamorphose interne",consigne:"Explore lâ€™idÃ©e de Â« MÃ©tamorphose interne Â» dans un contexte mystÃ©rieux : quel impact sur l'intrigue ?"},
  {categorie:"Personnage inattendu",abstraction:"MÃ©tamorphose interne",consigne:"Explore lâ€™idÃ©e de Â« MÃ©tamorphose interne Â» dans un contexte dramatique : quel impact sur l'intrigue ?"},
  {categorie:"Personnage inattendu",abstraction:"MÃ©tamorphose interne",consigne:"Explore lâ€™idÃ©e de Â« MÃ©tamorphose interne Â» dans un contexte surrÃ©aliste : quel impact sur l'intrigue ?"},
  {categorie:"Personnage inattendu",abstraction:"MÃ©tamorphose interne",consigne:"Explore lâ€™idÃ©e de Â« MÃ©tamorphose interne Â» dans un contexte mystÃ©rieux : quel impact sur l'intrigue ?"},
  {categorie:"Personnage inattendu",abstraction:"MÃ©tamorphose interne",consigne:"Explore lâ€™idÃ©e de Â« MÃ©tamorphose interne Â» dans un contexte dramatique : quel impact sur l'intrigue ?"},
  {categorie:"Personnage inattendu",abstraction:"MÃ©tamorphose interne",consigne:"Explore lâ€™idÃ©e de Â« MÃ©tamorphose interne Â» dans un contexte surrÃ©aliste : quel impact sur l'intrigue ?"},
  {categorie:"Personnage inattendu",abstraction:"MÃ©tamorphose interne",consigne:"Explore lâ€™idÃ©e de Â« MÃ©tamorphose interne Â» dans un contexte mystÃ©rieux : quel impact sur l'intrigue ?"},
  {categorie:"Personnage inattendu",abstraction:"MÃ©tamorphose interne",consigne:"Explore lâ€™idÃ©e de Â« MÃ©tamorphose interne Â» dans un contexte dramatique : quel impact sur l'intrigue ?"},
  {categorie:"Personnage inattendu",abstraction:"MÃ©tamorphose interne",consigne:"Explore lâ€™idÃ©e de Â« MÃ©tamorphose interne Â» dans un contexte surrÃ©aliste : quel impact sur l'intrigue ?"},
  {categorie:"Personnage inattendu",abstraction:"MÃ©tamorphose interne",consigne:"Explore lâ€™idÃ©e de Â« MÃ©tamorphose interne Â» dans un contexte mystÃ©rieux : quel impact sur l'intrigue ?"},
  {categorie:"Personnage inattendu",abstraction:"MÃ©tamorphose interne",consigne:"Explore lâ€™idÃ©e de Â« MÃ©tamorphose interne Â» dans un contexte dramatique : quel impact sur l'intrigue ?"},
  {categorie:"Personnage inattendu",abstraction:"MÃ©tamorphose interne",consigne:"Explore lâ€™idÃ©e de Â« MÃ©tamorphose interne Â» dans un contexte surrÃ©aliste : quel impact sur l'intrigue ?"},
  {categorie:"Personnage inattendu",abstraction:"MÃ©tamorphose interne",consigne:"Explore lâ€™idÃ©e de Â« MÃ©tamorphose interne Â» dans un contexte mystÃ©rieux : quel impact sur l'intrigue ?"},
  {categorie:"Personnage inattendu",abstraction:"MÃ©tamorphose interne",consigne:"Explore lâ€™idÃ©e de Â« MÃ©tamorphose interne Â» dans un contexte dramatique : quel impact sur l'intrigue ?"},
  {categorie:"Personnage inattendu",abstraction:"MÃ©tamorphose interne",consigne:"Explore lâ€™idÃ©e de Â« MÃ©tamorphose interne Â» dans un contexte surrÃ©aliste : quel impact sur l'intrigue ?"},
  {categorie:"Personnage inattendu",abstraction:"MÃ©tamorphose interne",consigne:"Explore lâ€™idÃ©e de Â« MÃ©tamorphose interne Â» dans un contexte mystÃ©rieux : quel impact sur l'intrigue ?"},
  {categorie:"Personnage inattendu",abstraction:"MÃ©tamorphose interne",consigne:"Explore lâ€™idÃ©e de Â« MÃ©tamorphose interne Â» dans un contexte dramatique : quel impact sur l'intrigue ?"},
  {categorie:"Personnage inattendu",abstraction:"MÃ©tamorphose interne",consigne:"Explore lâ€™idÃ©e de Â« MÃ©tamorphose interne Â» dans un contexte surrÃ©aliste : quel impact sur l'intrigue ?"},
  {categorie:"Personnage inattendu",abstraction:"MÃ©tamorphose interne",consigne:"Explore lâ€™idÃ©e de Â« MÃ©tamorphose interne Â» dans un contexte mystÃ©rieux : quel impact sur l'intrigue ?"},
  {categorie:"Personnage inattendu",abstraction:"MÃ©tamorphose interne",consigne:"Explore lâ€™idÃ©e de Â« MÃ©tamorphose interne Â» dans un contexte dramatique : quel impact sur l'intrigue ?"},
  {categorie:"Personnage inattendu",abstraction:"MÃ©tamorphose interne",consigne:"Explore lâ€™idÃ©e de Â« MÃ©tamorphose interne Â» dans un contexte surrÃ©aliste : quel impact sur l'intrigue ?"},
  {categorie:"Personnage inattendu",abstraction:"MÃ©tamorphose interne",consigne:"Explore lâ€™idÃ©e de Â« MÃ©tamorphose interne Â» dans un contexte mystÃ©rieux : quel impact sur l'intrigue ?"},
  {categorie:"Personnage inattendu",abstraction:"MÃ©tamorphose interne",consigne:"Explore lâ€™idÃ©e de Â« MÃ©tamorphose interne Â» dans un contexte dramatique : quel impact sur l'intrigue ?"},
  {categorie:"Personnage inattendu",abstraction:"MÃ©tamorphose interne",consigne:"Explore lâ€™idÃ©e de Â« MÃ©tamorphose interne Â» dans un contexte surrÃ©aliste : quel impact sur l'intrigue ?"},
  {categorie:"Personnage inattendu",abstraction:"MÃ©tamorphose interne",consigne:"Explore lâ€™idÃ©e de Â« MÃ©tamorphose interne Â» dans un contexte mystÃ©rieux : quel impact sur l'intrigue ?"},
  {categorie:"Personnage inattendu",abstraction:"MÃ©tamorphose interne",consigne:"Explore lâ€™idÃ©e de Â« MÃ©tamorphose interne Â» dans un contexte dramatique : quel impact sur l'intrigue ?"},
  {categorie:"Personnage inattendu",abstraction:"MÃ©tamorphose interne",consigne:"Explore lâ€™idÃ©e de Â« MÃ©tamorphose interne Â» dans un contexte surrÃ©aliste : quel impact sur l'intrigue ?"},
  {categorie:"Personnage inattendu",abstraction:"MÃ©tamorphose interne",consigne:"Explore lâ€™idÃ©e de Â« MÃ©tamorphose interne Â» dans un contexte mystÃ©rieux : quel impact sur l'intrigue ?"},
  {categorie:"Personnage inattendu",abstraction:"MÃ©tamorphose interne",consigne:"Explore lâ€™idÃ©e de Â« MÃ©tamorphose interne Â» dans un contexte dramatique : quel impact sur l'intrigue ?"},
  {categorie:"Personnage inattendu",abstraction:"MÃ©tamorphose interne",consigne:"Explore lâ€™idÃ©e de Â« MÃ©tamorphose interne Â» dans un contexte surrÃ©aliste : quel impact sur l'intrigue ?"},
  {categorie:"Personnage inattendu",abstraction:"MÃ©tamorphose interne",consigne:"Explore lâ€™idÃ©e de Â« MÃ©tamorphose interne Â» dans un contexte mystÃ©rieux : quel impact sur l'intrigue ?"},
  {categorie:"Personnage inattendu",abstraction:"MÃ©tamorphose interne",consigne:"Explore lâ€™idÃ©e de Â« MÃ©tamorphose interne Â» dans un contexte dramatique : quel impact sur l'intrigue ?"},
  {categorie:"Personnage inattendu",abstraction:"MÃ©tamorphose interne",consigne:"Explore lâ€™idÃ©e de Â« MÃ©tamorphose interne Â» dans un contexte surrÃ©aliste : quel impact sur l'intrigue ?"},
  {categorie:"Personnage inattendu",abstraction:"MÃ©tamorphose interne",consigne:"Explore lâ€™idÃ©e de Â« MÃ©tamorphose interne Â» dans un contexte mystÃ©rieux : quel impact sur l'intrigue ?"},
  {categorie:"Personnage inattendu",abstraction:"MÃ©tamorphose interne",consigne:"Explore lâ€™idÃ©e de Â« MÃ©tamorphose interne Â» dans un contexte dramatique : quel impact sur l'intrigue ?"},
  {categorie:"Personnage inattendu",abstraction:"MÃ©tamorphose interne",consigne:"Explore lâ€™idÃ©e de Â« MÃ©tamorphose interne Â» dans un contexte surrÃ©aliste : quel impact sur l'intrigue ?"},
  {categorie:"Personnage inattendu",abstraction:"MÃ©tamorphose interne",consigne:"Explore lâ€™idÃ©e de Â« MÃ©tamorphose interne Â» dans un contexte mystÃ©rieux : quel impact sur l'intrigue ?"},
  {categorie:"Personnage inattendu",abstraction:"MÃ©tamorphose interne",consigne:"Explore lâ€™idÃ©e de Â« MÃ©tamorphose interne Â» dans un contexte dramatique : quel impact sur l'intrigue ?"},
  {categorie:"Personnage inattendu",abstraction:"MÃ©tamorphose interne",consigne:"Explore lâ€™idÃ©e de Â« MÃ©tamorphose interne Â» dans un contexte surrÃ©aliste : quel impact sur l'intrigue ?"},
  {categorie:"Personnage inattendu",abstraction:"MÃ©tamorphose interne",consigne:"Explore lâ€™idÃ©e de Â« MÃ©tamorphose interne Â» dans un contexte mystÃ©rieux : quel impact sur l'intrigue ?"},
  {categorie:"Personnage inattendu",abstraction:"MÃ©tamorphose interne",consigne:"Explore lâ€™idÃ©e de Â« MÃ©tamorphose interne Â» dans un contexte dramatique : quel impact sur l'intrigue ?"},
  {categorie:"Personnage inattendu",abstraction:"MÃ©tamorphose interne",consigne:"Explore lâ€™idÃ©e de Â« MÃ©tamorphose interne Â» dans un contexte surrÃ©aliste : quel impact sur l'intrigue ?"},
  {categorie:"Personnage inattendu",abstraction:"MÃ©tamorphose interne",consigne:"Explore lâ€™idÃ©e de Â« MÃ©tamorphose interne Â» dans un contexte mystÃ©rieux : quel impact sur l'intrigue ?"},
  {categorie:"Personnage inattendu",abstraction:"MÃ©tamorphose interne",consigne:"Explore lâ€™idÃ©e de Â« MÃ©tamorphose interne Â» dans un contexte dramatique : quel impact sur l'intrigue ?"},
  {categorie:"Personnage inattendu",abstraction:"MÃ©tamorphose interne",consigne:"Explore lâ€™idÃ©e de Â« MÃ©tamorphose interne Â» dans un contexte surrÃ©aliste : quel impact sur l'intrigue ?"},
  {categorie:"Personnage inattendu",abstraction:"MÃ©tamorphose interne",consigne:"Explore lâ€™idÃ©e de Â« MÃ©tamorphose interne Â» dans un contexte mystÃ©rieux : quel impact sur l'intrigue ?"},
  {categorie:"Personnage inattendu",abstraction:"MÃ©tamorphose interne",consigne:"Explore lâ€™idÃ©e de Â« MÃ©tamorphose interne Â» dans un contexte dramatique : quel impact sur l'intrigue ?"},
  {categorie:"Personnage inattendu",abstraction:"MÃ©tamorphose interne",consigne:"Explore lâ€™idÃ©e de Â« MÃ©tamorphose interne Â» dans un contexte surrÃ©aliste : quel impact sur l'intrigue ?"},
  {categorie:"Personnage inattendu",abstraction:"MÃ©tamorphose interne",consigne:"Explore lâ€™idÃ©e de Â« MÃ©tamorphose interne Â» dans un contexte mystÃ©rieux : quel impact sur l'intrigue ?"},
  {categorie:"Personnage inattendu",abstraction:"MÃ©tamorphose interne",consigne:"Explore lâ€™idÃ©e de Â« MÃ©tamorphose interne Â» dans un contexte dramatique : quel impact sur l'intrigue ?"},
  {categorie:"Personnage inattendu",abstraction:"MÃ©tamorphose interne",consigne:"Explore lâ€™idÃ©e de Â« MÃ©tamorphose interne Â» dans un contexte surrÃ©aliste : quel impact sur l'intrigue ?"},
  {categorie:"Personnage inattendu",abstraction:"MÃ©tamorphose interne",consigne:"Explore lâ€™idÃ©e de Â« MÃ©tamorphose interne Â» dans un contexte mystÃ©rieux : quel impact sur l'intrigue ?"},
  {categorie:"Personnage inattendu",abstraction:"MÃ©tamorphose interne",consigne:"Explore lâ€™idÃ©e de Â« MÃ©tamorphose interne Â» dans un contexte dramatique : quel impact sur l'intrigue ?"},
  {categorie:"Personnage inattendu",abstraction:"MÃ©tamorphose interne",consigne:"Explore lâ€™idÃ©e de Â« MÃ©tamorphose interne Â» dans un contexte surrÃ©aliste : quel impact sur l'intrigue ?"},
  {categorie:"Personnage inattendu",abstraction:"MÃ©tamorphose interne",consigne:"Explore lâ€™idÃ©e de Â« MÃ©tamorphose interne Â» dans un contexte mystÃ©rieux : quel impact sur l'intrigue ?"},
  {categorie:"Personnage inattendu",abstraction:"MÃ©tamorphose interne",consigne:"Explore lâ€™idÃ©e de Â« MÃ©tamorphose interne Â» dans un contexte dramatique : quel impact sur l'intrigue ?"},
  {categorie:"Personnage inattendu",abstraction:"MÃ©tamorphose interne",consigne:"Explore lâ€™idÃ©e de Â« MÃ©tamorphose interne Â» dans un contexte surrÃ©aliste : quel impact sur l'intrigue ?"},
  {categorie:"Personnage inattendu",abstraction:"MÃ©tamorphose interne",consigne:"Explore lâ€™idÃ©e de Â« MÃ©tamorphose interne Â» dans un contexte mystÃ©rieux : quel impact sur l'intrigue ?"},
  {categorie:"Personnage inattendu",abstraction:"MÃ©tamorphose interne",consigne:"Explore lâ€™idÃ©e de Â« MÃ©tamorphose interne Â» dans un contexte dramatique : quel impact sur l'intrigue ?"},
  {categorie:"Personnage inattendu",abstraction:"MÃ©tamorphose interne",consigne:"Explore lâ€™idÃ©e de Â« MÃ©tamorphose interne Â» dans un contexte surrÃ©aliste : quel impact sur l'intrigue ?"},
  {categorie:"Personnage inattendu",abstraction:"MÃ©tamorphose interne",consigne:"Explore lâ€™idÃ©e de Â« MÃ©tamorphose interne Â» dans un contexte mystÃ©rieux : quel impact sur l'intrigue ?"},
  {categorie:"Personnage inattendu",abstraction:"MÃ©tamorphose interne",consigne:"Explore lâ€™idÃ©e de Â« MÃ©tamorphose interne Â» dans un contexte dramatique : quel impact sur l'intrigue ?"},
  {categorie:"Personnage inattendu",abstraction:"MÃ©tamorphose interne",consigne:"Explore lâ€™idÃ©e de Â« MÃ©tamorphose interne Â» dans un contexte surrÃ©aliste : quel impact sur l'intrigue ?"},
  {categorie:"Personnage inattendu",abstraction:"MÃ©tamorphose interne",consigne:"Explore lâ€™idÃ©e de Â« MÃ©tamorphose interne Â» dans un contexte mystÃ©rieux : quel impact sur l'intrigue ?"},
  {categorie:"Personnage inattendu",abstraction:"MÃ©tamorphose interne",consigne:"Explore lâ€™idÃ©e de Â« MÃ©tamorphose interne Â» dans un contexte dramatique : quel impact sur l'intrigue ?"},
  {categorie:"Personnage inattendu",abstraction:"MÃ©tamorphose interne",consigne:"Explore lâ€™idÃ©e de Â« MÃ©tamorphose interne Â» dans un contexte surrÃ©aliste : quel impact sur l'intrigue ?"},
  {categorie:"Personnage inattendu",abstraction:"MÃ©tamorphose interne",consigne:"Explore lâ€™idÃ©e de Â« MÃ©tamorphose interne Â» dans un contexte mystÃ©rieux : quel impact sur l'intrigue ?"},
  {categorie:"Personnage inattendu",abstraction:"MÃ©tamorphose interne",consigne:"Explore lâ€™idÃ©e de Â« MÃ©tamorphose interne Â» dans un contexte dramatique : quel impact sur l'intrigue ?"},
  {categorie:"Personnage inattendu",abstraction:"MÃ©tamorphose interne",consigne:"Explore lâ€™idÃ©e de Â« MÃ©tamorphose interne Â» dans un contexte surrÃ©aliste : quel impact sur l'intrigue ?"},
  {categorie:"Personnage inattendu",abstraction:"MÃ©tamorphose interne",consigne:"Explore lâ€™idÃ©e de Â« MÃ©tamorphose interne Â» dans un contexte mystÃ©rieux : quel impact sur l'intrigue ?"},
  {categorie:"Personnage inattendu",abstraction:"MÃ©tamorphose interne",consigne:"Explore lâ€™idÃ©e de Â« MÃ©tamorphose interne Â» dans un contexte dramatique : quel impact sur l'intrigue ?"},
  {categorie:"Personnage inattendu",abstraction:"MÃ©tamorphose interne",consigne:"Explore lâ€™idÃ©e de Â« MÃ©tamorphose interne Â» dans un contexte surrÃ©aliste : quel impact sur l'intrigue ?"},
  {categorie:"Personnage inattendu",abstraction:"MÃ©tamorphose interne",consigne:"Explore lâ€™idÃ©e de Â« MÃ©tamorphose interne Â» dans un contexte mystÃ©rieux : quel impact sur l'intrigue ?"},
  {categorie:"Personnage inattendu",abstraction:"MÃ©tamorphose interne",consigne:"Explore lâ€™idÃ©e de Â« MÃ©tamorphose interne Â» dans un contexte dramatique : quel impact sur l'intrigue ?"},
  {categorie:"Personnage inattendu",abstraction:"MÃ©tamorphose interne",consigne:"Explore lâ€™idÃ©e de Â« MÃ©tamorphose interne Â» dans un contexte surrÃ©aliste : quel impact sur l'intrigue ?"},
  {categorie:"Personnage inattendu",abstraction:"MÃ©tamorphose interne",consigne:"Explore lâ€™idÃ©e de Â« MÃ©tamorphose interne Â» dans un contexte mystÃ©rieux : quel impact sur l'intrigue ?"},
  {categorie:"Personnage inattendu",abstraction:"MÃ©tamorphose interne",consigne:"Explore lâ€™idÃ©e de Â« MÃ©tamorphose interne Â» dans un contexte dramatique : quel impact sur l'intrigue ?"},
  {categorie:"Personnage inattendu",abstraction:"MÃ©tamorphose interne",consigne:"Explore lâ€™idÃ©e de Â« MÃ©tamorphose interne Â» dans un contexte surrÃ©aliste : quel impact sur l'intrigue ?"},
  {categorie:"Personnage inattendu",abstraction:"MÃ©tamorphose interne",consigne:"Explore lâ€™idÃ©e de Â« MÃ©tamorphose interne Â» dans un contexte mystÃ©rieux : quel impact sur l'intrigue ?"},
  {categorie:"Personnage inattendu",abstraction:"MÃ©tamorphose interne",consigne:"Explore lâ€™idÃ©e de Â« MÃ©tamorphose interne Â» dans un contexte dramatique : quel impact sur l'intrigue ?"},
  {categorie:"Personnage inattendu",abstraction:"MÃ©tamorphose interne",consigne:"Explore lâ€™idÃ©e de Â« MÃ©tamorphose interne Â» dans un contexte surrÃ©aliste : quel impact sur l'intrigue ?"},
  {categorie:"Personnage inattendu",abstraction:"MÃ©tamorphose interne",consigne:"Explore lâ€™idÃ©e de Â« MÃ©tamorphose interne Â» dans un contexte mystÃ©rieux : quel impact sur l'intrigue ?"},
  {categorie:"Personnage inattendu",abstraction:"MÃ©tamorphose interne",consigne:"Explore lâ€™idÃ©e de Â« MÃ©tamorphose interne Â» dans un contexte dramatique : quel impact sur l'intrigue ?"},
  {categorie:"Personnage inattendu",abstraction:"MÃ©tamorphose interne",consigne:"Explore lâ€™idÃ©e de Â« MÃ©tamorphose interne Â» dans un contexte surrÃ©aliste : quel impact sur l'intrigue ?"},
  {categorie:"Personnage inattendu",abstraction:"MÃ©tamorphose interne",consigne:"Explore lâ€™idÃ©e de Â« MÃ©tamorphose interne Â» dans un contexte mystÃ©rieux : quel impact sur l'intrigue ?"},
  {categorie:"Personnage inattendu",abstraction:"MÃ©tamorphose interne",consigne:"Explore lâ€™idÃ©e de Â« MÃ©tamorphose interne Â» dans un contexte dramatique : quel impact sur l'intrigue ?"},
  {categorie:"Personnage inattendu",abstraction:"MÃ©tamorphose interne",consigne:"Explore lâ€™idÃ©e de Â« MÃ©tamorphose interne Â» dans un contexte surrÃ©aliste : quel impact sur l'intrigue ?"},
  {categorie:"Personnage inattendu",abstraction:"MÃ©tamorphose interne",consigne:"Explore lâ€™idÃ©e de Â« MÃ©tamorphose interne Â» dans un contexte mystÃ©rieux : quel impact sur l'intrigue ?"},
  {categorie:"Personnage inattendu",abstraction:"MÃ©tamorphose interne",consigne:"Explore lâ€™idÃ©e de Â« MÃ©tamorphose interne Â» dans un contexte dramatique : quel impact sur l'intrigue ?"},
  {categorie:"Personnage inattendu",abstraction:"MÃ©tamorphose interne",consigne:"Explore lâ€™idÃ©e de Â« MÃ©tamorphose interne Â» dans un contexte surrÃ©aliste : quel impact sur l'intrigue ?"},
  {categorie:"Personnage inattendu",abstraction:"MÃ©tamorphose interne",consigne:"Explore lâ€™idÃ©e de Â« MÃ©tamorphose interne Â» dans un contexte mystÃ©rieux : quel impact sur l'intrigue ?"},
  {categorie:"Personnage inattendu",abstraction:"MÃ©tamorphose interne",consigne:"Explore lâ€™idÃ©e de Â« MÃ©tamorphose interne Â» dans un contexte dramatique : quel impact sur l'intrigue ?"},
  {categorie:"Personnage inattendu",abstraction:"MÃ©tamorphose interne",consigne:"Explore lâ€™idÃ©e de Â« MÃ©tamorphose interne Â» dans un contexte surrÃ©aliste : quel impact sur l'intrigue ?"},
  {categorie:"Personnage inattendu",abstraction:"MÃ©tamorphose interne",consigne:"Explore lâ€™idÃ©e de Â« MÃ©tamorphose interne Â» dans un contexte mystÃ©rieux : quel impact sur l'intrigue ?"},
  {categorie:"Personnage inattendu",abstraction:"MÃ©tamorphose interne",consigne:"Explore lâ€™idÃ©e de Â« MÃ©tamorphose interne Â» dans un contexte dramatique : quel impact sur l'intrigue ?"},
  {categorie:"Personnage inattendu",abstraction:"MÃ©tamorphose interne",consigne:"Explore lâ€™idÃ©e de Â« MÃ©tamorphose interne Â» dans un contexte surrÃ©aliste : quel impact sur l'intrigue ?"},
  {categorie:"Personnage inattendu",abstraction:"MÃ©tamorphose interne",consigne:"Explore lâ€™idÃ©e de Â« MÃ©tamorphose interne Â» dans un contexte mystÃ©rieux : quel impact sur l'intrigue ?"},
  {categorie:"Personnage inattendu",abstraction:"MÃ©tamorphose interne",consigne:"Explore lâ€™idÃ©e de Â« MÃ©tamorphose interne Â» dans un contexte dramatique : quel impact sur l'intrigue ?"},
  {categorie:"Personnage inattendu",abstraction:"MÃ©tamorphose interne",consigne:"Explore lâ€™idÃ©e de Â« MÃ©tamorphose interne Â» dans un contexte surrÃ©aliste : quel impact sur l'intrigue ?"},
  {categorie:"Personnage inattendu",abstraction:"MÃ©tamorphose interne",consigne:"Explore lâ€™idÃ©e de Â« MÃ©tamorphose interne Â» dans un contexte mystÃ©rieux : quel impact sur l'intrigue ?"},
  {categorie:"Personnage inattendu",abstraction:"MÃ©tamorphose interne",consigne:"Explore lâ€™idÃ©e de Â« MÃ©tamorphose interne Â» dans un contexte dramatique : quel impact sur l'intrigue ?"},
  {categorie:"Personnage inattendu",abstraction:"MÃ©tamorphose interne",consigne:"Explore lâ€™idÃ©e de Â« MÃ©tamorphose interne Â» dans un contexte surrÃ©aliste : quel impact sur l'intrigue ?"},
  {categorie:"Personnage inattendu",abstraction:"MÃ©tamorphose interne",consigne:"Explore lâ€™idÃ©e de Â« MÃ©tamorphose interne Â» dans un contexte mystÃ©rieux : quel impact sur l'intrigue ?"},
  {categorie:"Personnage inattendu",abstraction:"MÃ©tamorphose interne",consigne:"Explore lâ€™idÃ©e de Â« MÃ©tamorphose interne Â» dans un contexte dramatique : quel impact sur l'intrigue ?"},
  {categorie:"Personnage inattendu",abstraction:"MÃ©tamorphose interne",consigne:"Explore lâ€™idÃ©e de Â« MÃ©tamorphose interne Â» dans un contexte surrÃ©aliste : quel impact sur l'intrigue ?"},
  {categorie:"Personnage inattendu",abstraction:"MÃ©tamorphose interne",consigne:"Explore lâ€™idÃ©e de Â« MÃ©tamorphose interne Â» dans un contexte mystÃ©rieux : quel impact sur l'intrigue ?"},
  {categorie:"Personnage inattendu",abstraction:"MÃ©tamorphose interne",consigne:"Explore lâ€™idÃ©e de Â« MÃ©tamorphose interne Â» dans un contexte dramatique : quel impact sur l'intrigue ?"},
  {categorie:"Personnage inattendu",abstraction:"MÃ©tamorphose interne",consigne:"Explore lâ€™idÃ©e de Â« MÃ©tamorphose interne Â» dans un contexte surrÃ©aliste : quel impact sur l'intrigue ?"},
  {categorie:"Personnage inattendu",abstraction:"MÃ©tamorphose interne",consigne:"Explore lâ€™idÃ©e de Â« MÃ©tamorphose interne Â» dans un contexte mystÃ©rieux : quel impact sur l'intrigue ?"},
  {categorie:"Personnage inattendu",abstraction:"MÃ©tamorphose interne",consigne:"Explore lâ€™idÃ©e de Â« MÃ©tamorphose interne Â» dans un contexte dramatique : quel impact sur l'intrigue ?"},
  {categorie:"Personnage inattendu",abstraction:"MÃ©tamorphose interne",consigne:"Explore lâ€™idÃ©e de Â« MÃ©tamorphose interne Â» dans un contexte surrÃ©aliste : quel impact sur l'intrigue ?"},
  {categorie:"Personnage inattendu",abstraction:"MÃ©tamorphose interne",consigne:"Explore lâ€™idÃ©e de Â« MÃ©tamorphose interne Â» dans un contexte mystÃ©rieux : quel impact sur l'intrigue ?"},
  {categorie:"Personnage inattendu",abstraction:"MÃ©tamorphose interne",consigne:"Explore lâ€™idÃ©e de Â« MÃ©tamorphose interne Â» dans un contexte dramatique : quel impact sur l'intrigue ?"},
  {categorie:"Personnage inattendu",abstraction:"MÃ©tamorphose interne",consigne:"Explore lâ€™idÃ©e de Â« MÃ©tamorphose interne Â» dans un contexte surrÃ©aliste : quel impact sur l'intrigue ?"},
  {categorie:"Personnage inattendu",abstraction:"MÃ©tamorphose interne",consigne:"Explore lâ€™idÃ©e de Â« MÃ©tamorphose interne Â» dans un contexte mystÃ©rieux : quel impact sur l'intrigue ?"},
  {categorie:"Personnage inattendu",abstraction:"MÃ©tamorphose interne",consigne:"Explore lâ€™idÃ©e de Â« MÃ©tamorphose interne Â» dans un contexte dramatique : quel impact sur l'intrigue ?"},
  {categorie:"Personnage inattendu",abstraction:"MÃ©tamorphose interne",consigne:"Explore lâ€™idÃ©e de Â« MÃ©tamorphose interne Â» dans un contexte surrÃ©aliste : quel impact sur l'intrigue ?"},
  {categorie:"Personnage inattendu",abstraction:"MÃ©tamorphose interne",consigne:"Explore lâ€™idÃ©e de Â« MÃ©tamorphose interne Â» dans un contexte mystÃ©rieux : quel impact sur l'intrigue ?"},
  {categorie:"Personnage inattendu",abstraction:"MÃ©tamorphose interne",consigne:"Explore lâ€™idÃ©e de Â« MÃ©tamorphose interne Â» dans un contexte dramatique : quel impact sur l'intrigue ?"},
  {categorie:"Personnage inattendu",abstraction:"MÃ©tamorphose interne",consigne:"Explore lâ€™idÃ©e de Â« MÃ©tamorphose interne Â» dans un contexte surrÃ©aliste : quel impact sur l'intrigue ?"},
  {categorie:"Personnage inattendu",abstraction:"MÃ©tamorphose interne",consigne:"Explore lâ€™idÃ©e de Â« MÃ©tamorphose interne Â» dans un contexte mystÃ©rieux : quel impact sur l'intrigue ?"},
  {categorie:"Personnage inattendu",abstraction:"MÃ©tamorphose interne",consigne:"Explore lâ€™idÃ©e de Â« MÃ©tamorphose interne Â» dans un contexte dramatique : quel impact sur l'intrigue ?"},
  {categorie:"Personnage inattendu",abstraction:"MÃ©tamorphose interne",consigne:"Explore lâ€™idÃ©e de Â« MÃ©tamorphose interne Â» dans un contexte surrÃ©aliste : quel impact sur l'intrigue ?"},
  {categorie:"Personnage inattendu",abstraction:"MÃ©tamorphose interne",consigne:"Explore lâ€™idÃ©e de Â« MÃ©tamorphose interne Â» dans un contexte mystÃ©rieux : quel impact sur l'intrigue ?"},
  {categorie:"Personnage inattendu",abstraction:"MÃ©tamorphose interne",consigne:"Explore lâ€™idÃ©e de Â« MÃ©tamorphose interne Â» dans un contexte dramatique : quel impact sur l'intrigue ?"},
  {categorie:"Personnage inattendu",abstraction:"MÃ©tamorphose interne",consigne:"Explore lâ€™idÃ©e de Â« MÃ©tamorphose interne Â» dans un contexte surrÃ©aliste : quel impact sur l'intrigue ?"},
  {categorie:"Personnage inattendu",abstraction:"MÃ©tamorphose interne",consigne:"Explore lâ€™idÃ©e de Â« MÃ©tamorphose interne Â» dans un contexte mystÃ©rieux : quel impact sur l'intrigue ?"},
  {categorie:"Personnage inattendu",abstraction:"MÃ©tamorphose interne",consigne:"Explore lâ€™idÃ©e de Â« MÃ©tamorphose interne Â» dans un contexte dramatique : quel impact sur l'intrigue ?"},
  {categorie:"Personnage inattendu",abstraction:"MÃ©tamorphose interne",consigne:"Explore lâ€™idÃ©e de Â« MÃ©tamorphose interne Â» dans un contexte surrÃ©aliste : quel impact sur l'intrigue ?"},
  {categorie:"Personnage inattendu",abstraction:"MÃ©tamorphose interne",consigne:"Explore lâ€™idÃ©e de Â« MÃ©tamorphose interne Â» dans un contexte mystÃ©rieux : quel impact sur l'intrigue ?"},
  {categorie:"Personnage inattendu",abstraction:"MÃ©tamorphose interne",consigne:"Explore lâ€™idÃ©e de Â« MÃ©tamorphose interne Â» dans un contexte dramatique : quel impact sur l'intrigue ?"},
  {categorie:"Personnage inattendu",abstraction:"MÃ©tamorphose interne",consigne:"Explore lâ€™idÃ©e de Â« MÃ©tamorphose interne Â» dans un contexte surrÃ©aliste : quel impact sur l'intrigue ?"},
  {categorie:"Personnage inattendu",abstraction:"MÃ©tamorphose interne",consigne:"Explore lâ€™idÃ©e de Â« MÃ©tamorphose interne Â» dans un contexte mystÃ©rieux : quel impact sur l'intrigue ?"},
  {categorie:"Personnage inattendu",abstraction:"MÃ©tamorphose interne",consigne:"Explore lâ€™idÃ©e de Â« MÃ©tamorphose interne Â» dans un contexte dramatique : quel impact sur l'intrigue ?"},
  {categorie:"Personnage inattendu",abstraction:"MÃ©tamorphose interne",consigne:"Explore lâ€™idÃ©e de Â« MÃ©tamorphose interne Â» dans un contexte surrÃ©aliste : quel impact sur l'intrigue ?"},
  {categorie:"Personnage inattendu",abstraction:"MÃ©tamorphose interne",consigne:"Explore lâ€™idÃ©e de Â« MÃ©tamorphose interne Â» dans un contexte mystÃ©rieux : quel impact sur l'intrigue ?"},
  {categorie:"Personnage inattendu",abstraction:"MÃ©tamorphose interne",consigne:"Explore lâ€™idÃ©e de Â« MÃ©tamorphose interne Â» dans un contexte dramatique : quel impact sur l'intrigue ?"},
  {categorie:"Personnage inattendu",abstraction:"MÃ©tamorphose interne",consigne:"Explore lâ€™idÃ©e de Â« MÃ©tamorphose interne Â» dans un contexte surrÃ©aliste : quel impact sur l'intrigue ?"},
  {categorie:"Personnage inattendu",abstraction:"MÃ©tamorphose interne",consigne:"Explore lâ€™idÃ©e de Â« MÃ©tamorphose interne Â» dans un contexte mystÃ©rieux : quel impact sur l'intrigue ?"},
  {categorie:"Personnage inattendu",abstraction:"MÃ©tamorphose interne",consigne:"Explore lâ€™idÃ©e de Â« MÃ©tamorphose interne Â» dans un contexte dramatique : quel impact sur l'intrigue ?"},
  {categorie:"Personnage inattendu",abstraction:"MÃ©tamorphose interne",consigne:"Explore lâ€™idÃ©e de Â« MÃ©tamorphose interne Â» dans un contexte surrÃ©aliste : quel impact sur l'intrigue ?"},
  {categorie:"Personnage inattendu",abstraction:"MÃ©tamorphose interne",consigne:"Explore lâ€™idÃ©e de Â« MÃ©tamorphose interne Â» dans un contexte mystÃ©rieux : quel impact sur l'intrigue ?"},
  {categorie:"Personnage inattendu",abstraction:"MÃ©tamorphose interne",consigne:"Explore lâ€™idÃ©e de Â« MÃ©tamorphose interne Â» dans un contexte dramatique : quel impact sur l'intrigue ?"},
  {categorie:"Personnage inattendu",abstraction:"MÃ©tamorphose interne",consigne:"Explore lâ€™idÃ©e de Â« MÃ©tamorphose interne Â» dans un contexte surrÃ©aliste : quel impact sur l'intrigue ?"},
  {categorie:"Personnage inattendu",abstraction:"MÃ©tamorphose interne",consigne:"Explore lâ€™idÃ©e de Â« MÃ©tamorphose interne Â» dans un contexte mystÃ©rieux : quel impact sur l'intrigue ?"},
  {categorie:"Personnage inattendu",abstraction:"MÃ©tamorphose interne",consigne:"Explore lâ€™idÃ©e de Â« MÃ©tamorphose interne Â» dans un contexte dramatique : quel impact sur l'intrigue ?"},
  {categorie:"Personnage inattendu",abstraction:"MÃ©tamorphose interne",consigne:"Explore lâ€™idÃ©e de Â« MÃ©tamorphose interne Â» dans un contexte surrÃ©aliste : quel impact sur l'intrigue ?"},
  {categorie:"Personnage inattendu",abstraction:"MÃ©tamorphose interne",consigne:"Explore lâ€™idÃ©e de Â« MÃ©tamorphose interne Â» dans un contexte mystÃ©rieux : quel impact sur l'intrigue ?"},
  {categorie:"Personnage inattendu",abstraction:"MÃ©tamorphose interne",consigne:"Explore lâ€™idÃ©e de Â« MÃ©tamorphose interne Â» dans un contexte dramatique : quel impact sur l'intrigue ?"},
  {categorie:"Personnage inattendu",abstraction:"MÃ©tamorphose interne",consigne:"Explore lâ€™idÃ©e de Â« MÃ©tamorphose interne Â» dans un contexte surrÃ©aliste : quel impact sur l'intrigue ?"},
  {categorie:"Personnage inattendu",abstraction:"MÃ©tamorphose interne",consigne:"Explore lâ€™idÃ©e de Â« MÃ©tamorphose interne Â» dans un contexte mystÃ©rieux : quel impact sur l'intrigue ?"},
  {categorie:"Personnage inattendu",abstraction:"MÃ©tamorphose interne",consigne:"Explore lâ€™idÃ©e de Â« MÃ©tamorphose interne Â» dans un contexte dramatique : quel impact sur l'intrigue ?"},
  {categorie:"Personnage inattendu",abstraction:"MÃ©tamorphose interne",consigne:"Explore lâ€™idÃ©e de Â« MÃ©tamorphose interne Â» dans un contexte surrÃ©aliste : quel impact sur l'intrigue ?"},
  {categorie:"Personnage inattendu",abstraction:"MÃ©tamorphose interne",consigne:"Explore lâ€™idÃ©e de Â« MÃ©tamorphose interne Â» dans un contexte mystÃ©rieux : quel impact sur l'intrigue ?"},
  {categorie:"Personnage inattendu",abstraction:"MÃ©tamorphose interne",consigne:"Explore lâ€™idÃ©e de Â« MÃ©tamorphose interne Â» dans un contexte dramatique : quel impact sur l'intrigue ?"},
  {categorie:"Personnage inattendu",abstraction:"MÃ©tamorphose interne",consigne:"Explore lâ€™idÃ©e de Â« MÃ©tamorphose interne Â» dans un contexte surrÃ©aliste : quel impact sur l'intrigue ?"},
  {categorie:"Personnage inattendu",abstraction:"MÃ©tamorphose interne",consigne:"Explore lâ€™idÃ©e de Â« MÃ©tamorphose interne Â» dans un contexte mystÃ©rieux : quel impact sur l'intrigue ?"},
  {categorie:"Personnage inattendu",abstraction:"MÃ©tamorphose interne",consigne:"Explore lâ€™idÃ©e de Â« MÃ©tamorphose interne Â» dans un contexte dramatique : quel impact sur l'intrigue ?"},
  {categorie:"Personnage inattendu",abstraction:"MÃ©tamorphose interne",consigne:"Explore lâ€™idÃ©e de Â« MÃ©tamorphose interne Â» dans un contexte surrÃ©aliste : quel impact sur l'intrigue ?"},
  {categorie:"Personnage inattendu",abstraction:"MÃ©tamorphose interne",consigne:"Explore lâ€™idÃ©e de Â« MÃ©tamorphose interne Â» dans un contexte mystÃ©rieux : quel impact sur l'intrigue ?"},
  {categorie:"Personnage inattendu",abstraction:"MÃ©tamorphose interne",consigne:"Explore lâ€™idÃ©e de Â« MÃ©tamorphose interne Â» dans un contexte dramatique : quel impact sur l'intrigue ?"},
  {categorie:"Personnage inattendu",abstraction:"MÃ©tamorphose interne",consigne:"Explore lâ€™idÃ©e de Â« MÃ©tamorphose interne Â» dans un contexte surrÃ©aliste : quel impact sur l'intrigue ?"},
  {categorie:"Personnage inattendu",abstraction:"MÃ©tamorphose interne",consigne:"Explore lâ€™idÃ©e de Â« MÃ©tamorphose interne Â» dans un contexte mystÃ©rieux : quel impact sur l'intrigue ?"},
  {categorie:"Personnage inattendu",abstraction:"MÃ©tamorphose interne",consigne:"Explore lâ€™idÃ©e de Â« MÃ©tamorphose interne Â» dans un contexte dramatique : quel impact sur l'intrigue ?"},
  {categorie:"Personnage inattendu",abstraction:"MÃ©tamorphose interne",consigne:"Explore lâ€™idÃ©e de Â« MÃ©tamorphose interne Â» dans un contexte surrÃ©aliste : quel impact sur l'intrigue ?"},
  {categorie:"Personnage inattendu",abstraction:"MÃ©tamorphose interne",consigne:"Explore lâ€™idÃ©e de Â« MÃ©tamorphose interne Â» dans un contexte mystÃ©rieux : quel impact sur l'intrigue ?"},
  {categorie:"Personnage inattendu",abstraction:"MÃ©tamorphose interne",consigne:"Explore lâ€™idÃ©e de Â« MÃ©tamorphose interne Â» dans un contexte dramatique : quel impact sur l'intrigue ?"},
  {categorie:"Personnage inattendu",abstraction:"MÃ©tamorphose interne",consigne:"Explore lâ€™idÃ©e de Â« MÃ©tamorphose interne Â» dans un contexte surrÃ©aliste : quel impact sur l'intrigue ?"},
  {categorie:"Personnage inattendu",abstraction:"MÃ©tamorphose interne",consigne:"Explore lâ€™idÃ©e de Â« MÃ©tamorphose interne Â» dans un contexte mystÃ©rieux : quel impact sur l'intrigue ?"},
  {categorie:"Personnage inattendu",abstraction:"MÃ©tamorphose interne",consigne:"Explore lâ€™idÃ©e de Â« MÃ©tamorphose interne Â» dans un contexte dramatique : quel impact sur l'intrigue ?"},
  {categorie:"Personnage inattendu",abstraction:"MÃ©tamorphose interne",consigne:"Explore lâ€™idÃ©e de Â« MÃ©tamorphose interne Â» dans un contexte surrÃ©aliste : quel impact sur l'intrigue ?"},
  {categorie:"Personnage inattendu",abstraction:"MÃ©tamorphose interne",consigne:"Explore lâ€™idÃ©e de Â« MÃ©tamorphose interne Â» dans un contexte mystÃ©rieux : quel impact sur l'intrigue ?"},
  {categorie:"Personnage inattendu",abstraction:"MÃ©tamorphose interne",consigne:"Explore lâ€™idÃ©e de Â« MÃ©tamorphose interne Â» dans un contexte dramatique : quel impact sur l'intrigue ?"},
  {categorie:"Personnage inattendu",abstraction:"MÃ©tamorphose interne",consigne:"Explore lâ€™idÃ©e de Â« MÃ©tamorphose interne Â» dans un contexte surrÃ©aliste : quel impact sur l'intrigue ?"},
  {categorie:"Personnage inattendu",abstraction:"MÃ©tamorphose interne",consigne:"Explore lâ€™idÃ©e de Â« MÃ©tamorphose interne Â» dans un contexte mystÃ©rieux : quel impact sur l'intrigue ?"},
  {categorie:"Personnage inattendu",abstraction:"MÃ©tamorphose interne",consigne:"Explore lâ€™idÃ©e de Â« MÃ©tamorphose interne Â» dans un contexte dramatique : quel impact sur l'intrigue ?"},
  {categorie:"Personnage inattendu",abstraction:"MÃ©tamorphose interne",consigne:"Explore lâ€™idÃ©e de Â« MÃ©tamorphose interne Â» dans un contexte surrÃ©aliste : quel impact sur l'intrigue ?"},
  {categorie:"Personnage inattendu",abstraction:"MÃ©tamorphose interne",consigne:"Explore lâ€™idÃ©e de Â« MÃ©tamorphose interne Â» dans un contexte mystÃ©rieux : quel impact sur l'intrigue ?"},
];
module.exports = pool;
